### ISSUE TITLE
[ENH]: vim setup not working correctly

### ISSUE THREAD

**Issue by iiHaSTe** [2KAbhishek/Oh-My-Termux#3]
### Description

after running this command
```bash
./setup.sh -a
# then
vim .
```
Show me this message after vim command
```bash
this plugin needs python3 compiled.
Press ENTER or type command to continue
```
![Screenshot_2022-08-14-13-00-09-18_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/88557866/184535847-00da1530-4eca-4296-b6a8-7aeb77baef71.jpg)

how i can fix that?? 🤔

**Comment by iiHaSTe** [comment]
well i fix this problem with this commands 
```bash
apt install vim-gtk -y
# then install websockets
pip install websockets
# finally just install vim pluging
vim +PlugInstall
```

and Sorry for the trouble 😅

**Comment by 2KAbhishek** [comment]
Thanks so much for pointing this out @DasTech7 , the problem was with the Ghosttext plugin in vim, I have removed it, it's not that useful on termux anyways. 

Running the setup script now shouldn't cause this issue anymore.

**Comment by 2KAbhishek** [comment]
Also if you like vim, you can also try out my [neovim setup](https://github.com/2kabhishek/nvim)
It's my go to editor now. ❤️
