### ISSUE TITLE
Import PGP key error

### ISSUE THREAD

**Issue by I-am-monuk** [2KAbhishek/Oh-My-Termux#4]
![Screenshot_2022-10-25-09-48-42-45](https://user-images.githubusercontent.com/101424375/198762534-5cc670fa-5a08-4855-a6e5-caeeda65e2db.jpg)
After install Oh-My-Termux it is showing following error. When I enter 'y' it is showing more error.
How to fix it ?

error: main: key "998DE27318E867EA976BA877389CE ED64573DFCA" is unknown

::Import PGP key 998DE27318E867EA976BA877389CE ED64573DFCA? [Y/n] error: x11: key "998DE27318E

867EA976BA877389CEED64573DFCA" is unknown ::Import PGP key 998DE27318E867EA976BA877389CE ED64573DFCA? [Y/n] error: root: key "998DE27318 E867EA976BA877389CEED64573DFCA" is unknown :: Import PGP key 998DE27318E867EA976BA877389CE ED64573DFCA? [Y/n] error: tur: key "998DE27318E 867EA976BA877389CEED64573DFCA" is unknown :: Import PGP key 998DE27318E867EA976BA877389CE ED64573DFCA? [Y/n]

**Comment by 2KAbhishek** [comment]
seems to be a keyring issue, I'd suggest running a pkg update

also I think this issue is with your pkg setup, nothing to do with this repo

Closing
