### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by essamkafafy** [2KAbhishek/Oh-My-Termux#6]
### Description of the bug

Hi dear
Install the steps
When isntall exta
Make install something but get this erorr
![Screenshot_20230912_185048_Termux](https://github.com/2KAbhishek/termux2k/assets/3779214/02c0053b-2c57-4337-a47e-9b72ef5401b8)
 I hope can help me,
Regards

### Steps To Reproduce

3

**Comment by essamkafafy** [comment]
![Screenshot_20230912_185459_Termux](https://github.com/2KAbhishek/termux2k/assets/3779214/12965ed9-d3f8-4769-89eb-7f9bf80d7420)
After press enter

**Comment by 2KAbhishek** [comment]
Open nvim and try running :Lazy update

**Comment by essamkafafy** [comment]
Thank you
But after run the nivm
See this message 
![Screenshot_20230913_104756_Termux](https://github.com/2KAbhishek/termux2k/assets/3779214/69a2a2d9-12a9-468c-aced-9b2d0affff1d)

**Comment by 2KAbhishek** [comment]
Looks like you are trying to install coc.nvim which I have not tried, I'll recommend an issue on the original repo https://github.com/neoclide/coc.nvim
